services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: library
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
